### ISSUE TITLE
Formuller

### ISSUE THREAD

**Issue by hakanpolat** [odtu/ee464-cheatsheet#1]
Build içine 2 tane formül ekledim biri FB diot( commutationlı) birde FB thristor. Amacım hem commutation olmadığı zamanki formül hem de commutation veya firing angle nedeniyle kaybolan alanlarıda daha net görebilmek. Sağlama yapma amaçlı bu şekilde ekledim.  Hem bu sayede fazladan yer de kaplamayız commutation alan hesap formüllerinde.

**Comment by ozank** [comment]
Eline sağlık. Şunu tekrar hatırlatayım, tüm değişiklikler .tex dosyasına girmeli, çünkü sınav günü .tex dosyasını compile edip PDF çıktısını dağıtacağım. Klasör içindeki PDF dosyası sadece sizin görmeniz icin
