### ISSUE TITLE
Cheatsheet Büyüklüğü 

### ISSUE THREAD

**Issue by Mertkaracelebi** [odtu/ee464-cheatsheet#7]
Hocam cheatsheetin buyukluğu ne kadar olucak acaba ? Eğer bir sayfaysa su an cheatsheette çok fazla gereksiz şey var değişmesi gereken.

**Comment by ozank** [comment]
Evet 1 sayfa.
Ama devre şemalarını koymanıza gerek yok, soruda zaten veririm, keza harmonik tablolarını da sorarsam veririm.

Ozan

Info:http://keysan.me
